[package]
name = "kallisti-models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ruma = "0.6.2"
serde = "1.0.137"
validator = { version = "0.15.0", features = ["derive"] }
